### ISSUE TITLE
Hardcoded path to JSON

### ISSUE THREAD

**Issue by josecolella** [minimaxir/magic-the-gifening#2]
Hey @minimaxir,
Saw that you are using a hardcoded path to the JSON that is located inside your downloads directory. https://github.com/minimaxir/magic-the-gifening/blob/baf09e54088d27110965cebaf6b444b1a925898a/get_cardlist.py#L4 .

**Comment by minimaxir** [comment]
The JSON file itself is [currently] 28.4 MB, so the user has to download it themselves and change the path if they want to regenerate the file.
